package com.qfedu.dtboot.dao;

import com.qfedu.dtboot.entity.ScheduleJobLog;
import org.springframework.stereotype.Component;

@Component(value ="scheduleJobLogMapper")
public interface ScheduleJobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insert(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insertSelective(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    ScheduleJobLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKeySelective(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKey(ScheduleJobLog record);
}