package com.qfedu.dtboot.dao;

import com.qfedu.dtboot.entity.SysConfig;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value ="sysConfigMapper")
public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insert(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int insertSelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    SysConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Fri Mar 02 03:58:13 CST 2018
     */
    int updateByPrimaryKey(SysConfig record);

    /**
     *根据主键前缀查询配置列表
     * @param keyPrefix
     * @return
     */
    List<SysConfig> queryByKeyPrefix(String keyPrefix);
}